language: python
env:
  - PIP_PKGS="pep8 Django"
  - PIP_PKGS="pep8 Django==1.8"
install:
  - sudo apt-get install -y freetds-dev
  - pip install $PIP_PKGS -e .
script:
  - pep8 techloan_server
  - python runtests.py
