language: python
env:
  - PIP_PKGS="Django<3.0"
  - PIP_PKGS="Django<2.0"
install:
  - sudo apt-get install -y freetds-dev
  - pip install pycodestyle $PIP_PKGS -e .
script:
  - pycodestyle techloan_server
  - python runtests.py
